version: '3.7'

services:
  # nest:
  #   container_name: 'nest'
  #   build:
  #     context: .
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #     # - /usr/src/app/node_modules
  #   ports:
  #     - ${SERVER_PORT}:${SERVER_PORT}
  #     - 9229:9229
  #   command: npm run start:debug
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo:latest
    container_name: 'nest_mongo'
    volumes:
      - mongodb_data_container:/data/db
    # env_file:
    #   - .env
    environment:
      - MONGO_INITDB_DATABASE=todos_db
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
networks:
  webnet:
volumes:
  mongodb_data_container: